apiVersion: v1
kind: Service
metadata:
  name: ai-api
  labels:
    app: ai-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
