replicaCount: 2

image:
  repository: abdell001/ai-api
  tag: 815438ef14dbcc9bdb2b09cb6d865e54e9570d5f
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

redis:
  host: redis
  port: 6379

ollama:
  url: http://ollama:11434

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
